# Site settings
title: Another Side of Brilliant Me
subtitle: "User researcher, general nerd. Writes about gender, software, mental health and digital games."
email: chad@kitation.co.uk
description:
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title.html
paginate: 10
excerpt_separator: <!--more-->

url: "http://kitation.co.uk" # the base hostname & protocol for your site
twitter_username: kitation
github_username:  kitation

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
theme: jekyll-theme-cayman
