# Site settings
title: Another Side of Brilliant Me
subtitle: "Web developer, general nerd. Talks about gaming, gender and education."
email: chad@kitation.co.uk
description:
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title.html
paginate: 10
excerpt_separator: <!--more-->

url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kitation
github_username:  kitation

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
theme: jekyll-theme-cayman
