# Site settings
title: Reach Out To The Truth
subtitle: "Ruby web developer, Code Club volunteer, First Play Sheffield co-organiser. Into tech, gender, F1, videogames"
email: chad@kitation.co.uk
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title.html
paginate: 10
excerpt_separator: <!--more-->

url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kitation
github_username:  kitation

# Build settings
markdown: kramdown
